version = "v0.1.3"

[artifacts.x86_64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-detector-toy/releases/download/v0.1.3/hmt-detector-toy-v0.1.3-x86_64-unknown-linux-gnu.tar.gz"
hash = "735264ae82acfc00c8475a2588219a6e6c6fe344d2dcae929160c615c58e5755"

[artifacts.aarch64-unknown-linux-gnu]
url = "https://github.com/hummanta/hmt-detector-toy/releases/download/v0.1.3/hmt-detector-toy-v0.1.3-aarch64-unknown-linux-gnu.tar.gz"
hash = "0ff6f2d19d6ef92f1f2dbea7ef0000ae415d337e6d92536958672418a5b459c8"

[artifacts.x86_64-apple-darwin]
url = "https://github.com/hummanta/hmt-detector-toy/releases/download/v0.1.3/hmt-detector-toy-v0.1.3-x86_64-apple-darwin.tar.gz"
hash = "cc8e953bd11e2a5a0e672aa5b29264bee9eb91b1bd4cd9cf3dea33d657af600a"

[artifacts.aarch64-apple-darwin]
url = "https://github.com/hummanta/hmt-detector-toy/releases/download/v0.1.3/hmt-detector-toy-v0.1.3-aarch64-apple-darwin.tar.gz"
hash = "fb8d6152cf9d584732efd32b81e7bc799c6e4ff9a6f12defb3ebdc2c8a057728"

[artifacts.x86_64-pc-windows-msvc]
url = "https://github.com/hummanta/hmt-detector-toy/releases/download/v0.1.3/hmt-detector-toy-v0.1.3-x86_64-pc-windows-msvc.tar.gz"
hash = "60761140712e65f60b6551ed4042f39e2da49def2d45f7537e4cc918b15dd664"
